version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/codedeploy-app
hooks:
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 60
      runas: root
